### ISSUE TITLE
section - 3 - when the screen is bigger. You should see the content

### ISSUE THREAD

**Issue by bolom** [lobo-studio/lobo.studio#56]
http://quirktools.com/screenfly/#u=http%3A//lordalexworks.github.io/lobo/&w=375&h=667&a=37

i don't see the content

**Comment by bolom** [comment]
missing the arrow

**Comment by accetone** [comment]
@bolom content now appear on screens bigger then 360px. We don't need arrow on mobile, because content is bigger than one screen

**Comment by bolom** [comment]
https://lookback.io/watch/bqMjpJYAG3aT9tnKm

**Comment by bolom** [comment]
@accetone it's fixed?

**Comment by accetone** [comment]
@bolom yes
